[package]
name = "suru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.14", features = ["derive"] }
dialoguer = "0.10.1"
home = "0.5.3"
rusqlite = "0.28.0"
